Travelista/Travelista/urls.py
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.contrib.sites.models import Site
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

from apps.blog.sitemaps import BlogSitemap
from apps.mainPage.sitemaps import MainPageViewSitemap


def redirect_to_domain(request):
    current_site = Site.objects.get_current()
    redirect_url = f"https://{current_site.domain}"
    return RedirectView.as_view(url=redirect_url)(request)

sitemaps = {
    'index': MainPageViewSitemap,
    'blog': BlogSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.mainPage.urls')),
    path('blog/', include('apps.blog.urls')),

    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
    re_path(r'^robots\.txt', include('robots.urls')),

    path('accounts/', include('allauth.urls')),
    path('accounts/', include('allauth.socialaccount.urls')),
    path('', redirect_to_domain,),
]

# Manage static files and url through nginx in production
if settings.DEBUG == True:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls"))
    ]

Travelista/apps/blog/urls.py
from django.urls import path
from .views import *

app_name = 'blog'

urlpatterns = [
    path('', blog_home, name='index'),
    path('single/<int:pid>', blog_single, name='single'),
    path('category/<str:cat_name>', blog_home, name='category'),
    path('author/<str:author>', blog_home, name='author'),
    path('search/',blog_search,name='search'),
]

Travelista/blog/urls.py
from django.urls import path
from blog.views import *

app_name = 'blog'

urlpatterns = [
    path('', blog_home, name='index'),
    path('single/<int:pid>', blog_single, name='single'),
    path('category/<str:cat_name>', blog_home, name='category'),
    path('author/<str:author>', blog_home, name='author'),
    path('search/',blog_search,name='search'),
]

Travelista/mainPage/urls.py
from django.urls import path
from mainPage.views import *

app_name = 'index'

urlpatterns = [
    path('', mainPage, name='Travelista'),
    path('about/', about, name='about'),
    path('contact/', contact, name='contact'),
]

Travelista/apps/blog/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.db.models import Q
from django.urls import reverse
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from taggit.managers import TaggableManager
from ckeditor.fields import RichTextField


class PostManager(models.Manager):
    def showable(self):
        current_datetime = timezone.now()
        posts = self.filter(Q(status=Post.StatusChoices.PUBLISHED) &
                            Q(published_date__lt=current_datetime)).order_by('-published_date')
        return posts

class Category(models.Model):
    name = models.CharField(_('Name'), max_length=255)
    active = models.BooleanField(_('Active'), default=True)

    class Meta:
        ordering = ['name']
        verbose_name = _('category')
        verbose_name_plural = _('categories')

    def __str__(self) -> str:
        return self.name


class Post(models.Model):
    class StatusChoices(models.TextChoices):
        DRAFT = _('Draft')
        PUBLISHED = _('Published')

    img = models.ImageField(_('Image'), upload_to='blog_media/', default='blog_media/default.jpg')
    author = models.ForeignKey(get_user_model(), on_delete=models.SET_NULL, null=True, blank=False)
    title = models.CharField(_('Title'), max_length=255)
    slug = models.SlugField(_('Slug'), max_length=255, allow_unicode=True, unique_for_date='published_date')
    content = RichTextField(_('Content'), )
    tag = TaggableManager(_('Tag'), blank=True)
    category = models.ManyToManyField(Category)
    counted_views = models.IntegerField(_('Counted Views'), default=0)
    status = models.CharField(_('Status'), default=StatusChoices.DRAFT, max_length=15, null=False, choices=StatusChoices.choices)
    # status = models.BooleanField(_('Status'), default=False)
    published_date = models.DateTimeField(_('Publish Date'), null=True, blank=True)
    created_date = models.DateTimeField(_('Created Date'), auto_now_add=True)
    updated_date = models.DateTimeField(_('Updated Date'), auto_now=True)

    posts = PostManager()
    objects = models.Manager()

    class Meta:
        verbose_name = _('Post')
        verbose_name_plural = _('Posts')
        ordering = ('-published_date',)

    def get_absolute_url(self):
        return reverse('blog:single', args=[
            self.id,
        ])

    def __str__(self) -> str:
        return self.title

Travelista/apps/blog/views.py
from django.shortcuts import render, get_object_or_404
from itertools import chain
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.utils import timezone   #This is for filtering by published_date
from .models import Post


def blog_home(request, **kwargs):
    posts = Post.posts.showable().select_related('author')
    if cat_name := kwargs.get('cat_name'):
        posts = posts.filter(category__name=cat_name)
    if author := kwargs.get('author'):
        posts = posts.filter(author__username=author)

    posts = Paginator(posts, 5)
    try:
        page_number = request.GET.get('page')
        posts = posts.get_page(page_number)
    except PageNotAnInteger:
        posts = posts.get_page(1)
    except EmptyPage:
        posts = posts.get_page(1)

    content = {'posts': posts}
    return render(request, 'blog/blog-home.html', content)


def blog_single(request, **kwargs):
    posts = Post.posts.showable()
    content = {'posts': posts }
    if pid := kwargs.get('pid'):
        # post = posts.get(id=pid)
        post = get_object_or_404(posts, pk=pid)
        post.counted_views += 1
        post.save()
        content['post'] = post
    return render(request, 'blog/blog-single.html', content)


def blog_search(request):
    posts = Post.posts.showable()
    if request.method == 'GET':
        if s := request.GET.get('search'):
            posts = posts.filter(content__icontains=s)
            posts = chain(Post.objects.filter(title__icontains=s), posts)

    # posts = Paginator(posts,3)
    # try:
    #     page_number = request.GET.get('page')
    #     posts = posts.get_page(page_number)
    # except PageNotAnInteger:
    #     posts = posts.get_page(1)
    # except EmptyPage:
    #     posts = posts.get_page(1)

    context = {'posts': posts}
    return render(request, 'blog/blog-home.html', context)

Travelista/blog/views.py
from django.shortcuts import render, get_object_or_404
from blog.models import Post
from itertools import chain
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.utils import timezone   #This is for filtering by published_date


def blog_home(request, **kwargs):
    current_datetime = timezone.now()    #This is for filtering by published_date
    posts = Post.objects.filter(published_date__lt=current_datetime)     #This is for filtering by published_date
    posts = posts.filter(status=1).order_by('-published_date')
    if cat_name := kwargs.get('cat_name'):
        posts = posts.filter(category__name=cat_name)
    if author := kwargs.get('author'):
        posts = posts.filter(author__username=author)

    posts = Paginator(posts, 5)
    try:
        page_number = request.GET.get('page')
        posts = posts.get_page(page_number)
    except PageNotAnInteger:
        posts = posts.get_page(1)
    except EmptyPage:
        posts = posts.get_page(1)

    content = {'posts': posts}
    return render(request, 'blog/blog-home.html', content)


def blog_single(request, **kwargs):
    current_datetime = timezone.now()    #This is for filtering by published_date
    posts = Post.objects.filter(published_date__lt=current_datetime)
    posts = posts.filter(status=1)
    if pid := kwargs.get('pid'):
        post = posts.get(id=pid)
        post.counted_views += 1
        post.save()
        # post = get_object_or_404(posts, pk=pid)
    content = {'post': post, 'posts': posts }
    return render(request, 'blog/blog-single.html', content)


def blog_search(request):
    posts = Post.objects.filter(status=1)
    if request.method == 'GET':
        if s := request.GET.get('search'):
            posts = posts.filter(content__icontains=s)
            posts = chain(Post.objects.filter(title__icontains=s), posts)

    # posts = Paginator(posts,3)
    # try:
    #     page_number = request.GET.get('page')
    #     posts = posts.get_page(page_number)
    # except PageNotAnInteger:
    #     posts = posts.get_page(1)
    # except EmptyPage:
    #     posts = posts.get_page(1)

    context = {'posts': posts}
    return render(request, 'blog/blog-home.html', context)

Travelista/templates/blog/blog-ads.html
{% load static %}

<div class="single-sidebar-widget ads-widget">
    <a href="#"><img class="img-fluid" src="{% static 'img/blog/ads-banner.jpg' %}" alt=""></a>
</div>

Travelista/templates/blog/blog-cloud.html
{% load static blog_tags %}

<div class="single-sidebar-widget tag-cloud-widget">
    <h4 class="tagcloud-title">Tag Clouds</h4>
    <ul>
        {% for tag in all_tags %}
            <li><a href="#">{{ tag.name }}</a> <span class="badge text-bg-secondary">{{ tag.num_posts }}</span></li>

        {% endfor %}
    </ul>
</div>

Travelista/templates/blog/blog-home-top-category.html
{% load static %}

<section class="top-category-widget-area pt-90 pb-90 ">
	<div class="container">
		<div class="row">		
			<div class="col-lg-4">
				<div class="single-cat-widget">
					<div class="content relative">
						<div class="overlay overlay-bg"></div>
						<a href="#" target="_blank">
							<div class="thumb">
								<img class="content-image img-fluid d-block mx-auto" src="{% static 'img/blog/cat-widget1.jpg' %}" alt="">
							</div>
							<div class="content-details">
							<h4 class="content-title mx-auto text-uppercase">Social life</h4>
							<span></span>								        
							<p>Enjoy your social life together</p>
							</div>
						</a>
					</div>
				</div>
			</div>
			<div class="col-lg-4">
				<div class="single-cat-widget">
					<div class="content relative">
						<div class="overlay overlay-bg"></div>
						<a href="#" target="_blank">
							<div class="thumb">
								<img class="content-image img-fluid d-block mx-auto" src="{% static 'img/blog/cat-widget2.jpg' %}" alt="">
							</div>
							<div class="content-details">
							<h4 class="content-title mx-auto text-uppercase">Politics</h4>
							<span></span>								        
							<p>Be a part of politics</p>
							</div>
						</a>
					</div>
				</div>
			</div>
			<div class="col-lg-4">
				<div class="single-cat-widget">
					<div class="content relative">
						<div class="overlay overlay-bg"></div>
						<a href="#" target="_blank">
							<div class="thumb">
								<img class="content-image img-fluid d-block mx-auto" src="{% static 'img/blog/cat-widget3.jpg' %}" alt="">
							</div>
							<div class="content-details">
							<h4 class="content-title mx-auto text-uppercase">Food</h4>
							<span></span>
							<p>Let the food be finished</p>
							</div>
						</a>
					</div>
				</div>
			</div>												
		</div>
	</div>	
</section>

Travelista/templates/blog/blog-home.html
{% extends 'base.html' %}
{% load static blog_tags %}

{% block content %}
<!-- start banner Area -->
<section class="banner-area relative blog-home-banner" id="home">	
	<div class="overlay overlay-bg"></div>
	<div class="container">				
		<div class="row d-flex align-items-center justify-content-center">
			<div class="about-content blog-header-content col-lg-12">
				<h1 class="text-white">
					Dude You’re Getting
					a Telescope				
				</h1>	
				<p class="text-white">
					There is a moment in the life of any aspiring astronomer that it is time to buy that first
				</p>							
			</div>	
		</div>
	</div>
</section>
<!-- End banner Area -->

<!-- Start top-category-widget Area -->
{% include 'blog/blog-home-top-category.html' %}
<!-- End top-category-widget Area -->

<!-- Start post-content Area -->
<section class="post-content-area">
	<div class="container">
		<div class="row">
			<div class="col-lg-8 posts-list">
				{% for post in posts  %}
				<div class="single-post row">
					<div class="col-lg-3  col-md-3 meta-details">
						<ul class="tags">
							{% for cat in post.category.all %}
							<li><a href="{% url 'blog:category' cat_name=cat %}">
								{{cat.name}}
								{% if not forloop.last %}, {% endif %}
							</a></li>
							{% endfor %}
						</ul>
						<div class="user-details row">
							<p class="user-name col-lg-12 col-md-12 col-6"><a href="#">{{post.author.get_full_name}}</a> <span class="lnr lnr-user"></span></p>
							<p class="date col-lg-12 col-md-12 col-6"><a href="#">{{post.published_date|date:"d M, Y"}}</a> <span class="lnr lnr-calendar-full"></span></p>
							<p class="view col-lg-12 col-md-12 col-6"><a href="#">{{post.counted_views}} Views</a> <span class="lnr lnr-eye"></span></p>
							<p class="comments col-lg-12 col-md-12 col-6"><a href="#">06 Comments</a> <span class="lnr lnr-bubble"></span></p>						
						</div>
					</div>
					<div class="col-lg-9 col-md-9 ">
						<div class="feature-img">
							<img class="img-fluid" src="{{post.img.url}}" alt="">
						</div>
						<a class="posts-title" href="{% url 'blog:single' pid=post.id %}"><h3>{{post.title}}</h3></a>
						<p class="excert">
							{{post.content|truncatewords:20|striptags}}
						</p>
						<a href="{% url 'blog:single' pid=post.id %}" class="primary-btn">View More</a>
					</div>
				</div>
				{% endfor %}
				
				{% include 'blog/blog-paginate.html' %}

			</div>
			<div class="col-lg-4 sidebar-widgets">
				<div class="widget-wrap">
					
					{% include 'blog/blog-search.html' %}
					
					{% include 'blog/blog-user.html' %}

					{% latest_posts 5 %}
					
					{% include 'blog/blog-ads.html' %}
					
					{% categories %}
					
					{% include 'blog/blog-newsletter.html' %}
					
					{% tag_cloud %}
					
				</div>
			</div>
		</div>
	</div>	
</section>
<!-- End post-content Area -->
{% endblock content %}

Travelista/templates/blog/blog-newsletter.html
{% load static %}

<div class="single-sidebar-widget newsletter-widget">
    <h4 class="newsletter-title">Newsletter</h4>
    <p>
        Here, I focus on a range of items and features that we use in life without
        giving them a second thought.
    </p>
    <div class="form-group d-flex flex-row">
        <div class="col-autos">
            <div class="input-group">
            <div class="input-group-prepend">
                <div class="input-group-text"><i class="fa fa-envelope" aria-hidden="true"></i>
            </div>
            </div>
            <input type="text" class="form-control" id="inlineFormInputGroup" placeholder="Enter email" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter email'" >
            </div>
        </div>
        <a href="#" class="bbtns">Subcribe</a>
    </div>	
    <p class="text-bottom">
        You can unsubscribe at any time
    </p>								
</div>

Travelista/templates/blog/blog-popular-post.html
{% load static %}

<div class="single-sidebar-widget popular-post-widget">
    <h4 class="popular-title">Latest Posts</h4>
    <div class="popular-post-list">
        {% for post in posts %}
            <div class="single-post-list d-flex flex-row align-items-center">
                <div class="thumb">
                    <img class="img-fluid" src="{{post.img.url}}" alt="">
                </div>
                <div class="details">
                    <a href="{% url 'blog:single' pid=post.id %}"><h6>{{post.title}}</h6></a>
                    <p>{{post.published_date|date:"d M, Y"}}</p>
                </div>
            </div>															
        {% endfor %}
    </div>
</div>

Travelista/templates/blog/blog-post-category.html
{% load static %}

<div class="single-sidebar-widget post-category-widget">
    <h4 class="category-title">Post Catgories</h4>
    <ul class="cat-list">
        {% for cat, count in categories.items %}
            <li>
                <a href="{% url 'blog:category' cat_name=cat %}" class="d-flex justify-content-between">
                    <p>{{cat}}</p>
                    <p>{{count}}</p>
                </a>
            </li>
        {% endfor %}
    </ul>
</div>	

Travelista/templates/blog/blog-search.html
{% load static %}

<div class="single-sidebar-widget search-widget">
    <form class="search-form" action="{% url 'blog:search' %}">
        <input placeholder="Search Posts" name="search" type="text" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Search Posts'" >
        <button type="submit"><i class="fa fa-search"></i></button>
    </form>
</div>

Travelista/templates/blog/blog-single.html
{% extends 'base.html' %}
{% load static blog_tags  %}

{% block content %}
<!-- start banner Area -->
<section class="relative about-banner">	
	<div class="overlay overlay-bg"></div>
	<div class="container">				
		<div class="row d-flex align-items-center justify-content-center">
			<div class="about-content col-lg-12">
				<h1 class="text-white">
					{{post.title}}
				</h1>	
				<p class="text-white link-nav"><a href="{% url 'index:Travelista' %}">Home </a>  <span class="lnr lnr-arrow-right"></span><a href="{% url 'blog:index' %}">Blog </a> <span class="lnr lnr-arrow-right"></span> <a href="{% url 'blog:single' pid=post.id %}">{{post.title}}</a></p>
			</div>	
		</div>
	</div>
</section>
<!-- End banner Area -->					  

<!-- Start post-content Area -->
<section class="post-content-area single-post-area">
	<div class="container">
		<div class="row">
			<div class="col-lg-8 posts-list">
				<div class="single-post row">
					<div class="col-lg-12">
						<div class="feature-img">
							<img class="img-fluid" src="{{post.img.url}}" alt="">
						</div>									
					</div>
					<div class="col-lg-3  col-md-3 meta-details">
						<ul class="tags">
							{% for cat in post.category.all %}
							<li><a href="{% url 'blog:category' cat_name=cat %}">
								{% if forloop.last %}
									{{cat.name}}
								{% else %}
									{{cat.name}}, 
								{% endif %}
							</a></li>
							{% endfor %}
						</ul>
						<div class="user-details row">
							<p class="user-name col-lg-12 col-md-12 col-6"><a href="#">{{post.author.get_full_name}}</a> <span class="lnr lnr-user"></span></p>
							<p class="date col-lg-12 col-md-12 col-6"><a href="#">{{post.published_date|date:"d M, Y"}}</a> <span class="lnr lnr-calendar-full"></span></p>
							<p class="view col-lg-12 col-md-12 col-6"><a href="#">{{post.counted_views}} Views</a> <span class="lnr lnr-eye"></span></p>
							<p class="comments col-lg-12 col-md-12 col-6"><a href="#">06 Comments</a> <span class="lnr lnr-bubble"></span></p>
							<ul class="social-links col-lg-12 col-md-12 col-6">
								<li><a href="#"><i class="fa fa-facebook"></i></a></li>
								<li><a href="#"><i class="fa fa-twitter"></i></a></li>
								<li><a href="#"><i class="fa fa-github"></i></a></li>
								<li><a href="#"><i class="fa fa-behance"></i></a></li>
							</ul>																				
						</div>
					</div>
					<div class="col-lg-9 col-md-9">
						<h3 class="mt-20 mb-20">{{post.title}}</h3>
						<p class="excert">
							{{post.content|safe}}
						</p>
					</div>
				</div>
				<div class="navigation-area">
					<div class="row">
						{% with prev_post=post|get_previous_post:posts %}
							{% if prev_post %}
						<div class="col-lg-6 col-md-6 col-12 nav-left flex-row d-flex justify-content-start align-items-center">
							<div class="thumb">
								<a href="{% url 'blog:single' pid=prev_post.id %}"><img class="img-fluid" src="{{prev_post.img.url}}" alt=""></a>
							</div>
							<div class="arrow">
								<a href="{% url 'blog:single' pid=prev_post.id %}"><span class="lnr text-white lnr-arrow-left"></span></a>
							</div>
							<div class="detials">
								<p>Prev Post</p>
								<a href="{% url 'blog:single' pid=prev_post.id %}"><h4>{{prev_post.title}}</h4></a>
							</div>
						</div>
							{% endif %}
						{% endwith %}
						{% with next_post=post|get_next_post:posts %}
        					{% if next_post %}
						<div class="col-lg-6 col-md-6 col-12 nav-right flex-row d-flex justify-content-end align-items-center">
							<div class="detials">
								<p>Next Post</p>
								<a href="{% url 'blog:single' pid=next_post.id %}"><h4>{{next_post.title}}</h4></a>
							</div>
							<div class="arrow">
								<a href="{% url 'blog:single' pid=next_post.id %}"><span class="lnr text-white lnr-arrow-right"></span></a>
							</div>
							<div class="thumb">
								<a href="{% url 'blog:single' pid=next_post.id %}"><img class="img-fluid" src="{{next_post.img.url}}" alt=""></a>
							</div>										
						</div>
							{% endif %}
    					{% endwith %}
					</div>
				</div>

                <!-- Comment Area -->

{#				<div class="comments-area">#}
{#					<h4>05 Comments</h4>#}
{#					<div class="comment-list">#}
{#						<div class="single-comment justify-content-between d-flex">#}
{#							<div class="user justify-content-between d-flex">#}
{#								<div class="thumb">#}
{#									<img src="{% static 'img/blog/c1.jpg' %}" alt="">#}
{#								</div>#}
{#								<div class="desc">#}
{#									<h5><a href="#">Emilly Blunt</a></h5>#}
{#									<p class="date">December 4, 2017 at 3:12 pm </p>#}
{#									<p class="comment">#}
{#										Never say goodbye till the end comes!#}
{#									</p>#}
{#								</div>#}
{#							</div>#}
{#							<div class="reply-btn">#}
{#									<a href="" class="btn-reply text-uppercase">reply</a> #}
{#							</div>#}
{#						</div>#}
{#					</div>	#}
{#					<div class="comment-list left-padding">#}
{#						<div class="single-comment justify-content-between d-flex">#}
{#							<div class="user justify-content-between d-flex">#}
{#								<div class="thumb">#}
{#									<img src="{% static 'img/blog/c2.jpg' %}" alt="">#}
{#								</div>#}
{#								<div class="desc">#}
{#									<h5><a href="#">Elsie Cunningham</a></h5>#}
{#									<p class="date">December 4, 2017 at 3:12 pm </p>#}
{#									<p class="comment">#}
{#										Never say goodbye till the end comes!#}
{#									</p>#}
{#								</div>#}
{#							</div>#}
{#							<div class="reply-btn">#}
{#									<a href="" class="btn-reply text-uppercase">reply</a> #}
{#							</div>#}
{#						</div>#}
{#					</div>	#}
{#					<div class="comment-list left-padding">#}
{#						<div class="single-comment justify-content-between d-flex">#}
{#							<div class="user justify-content-between d-flex">#}
{#								<div class="thumb">#}
{#									<img src="{% static 'img/blog/c3.jpg' %}" alt="">#}
{#								</div>#}
{#								<div class="desc">#}
{#									<h5><a href="#">Annie Stephens</a></h5>#}
{#									<p class="date">December 4, 2017 at 3:12 pm </p>#}
{#									<p class="comment">#}
{#										Never say goodbye till the end comes!#}
{#									</p>#}
{#								</div>#}
{#							</div>#}
{#							<div class="reply-btn">#}
{#									<a href="" class="btn-reply text-uppercase">reply</a> #}
{#							</div>#}
{#						</div>#}
{#					</div>	#}
{#					<div class="comment-list">#}
{#						<div class="single-comment justify-content-between d-flex">#}
{#							<div class="user justify-content-between d-flex">#}
{#								<div class="thumb">#}
{#									<img src="{% static 'img/blog/c4.jpg' %}" alt="">#}
{#								</div>#}
{#								<div class="desc">#}
{#									<h5><a href="#">Maria Luna</a></h5>#}
{#									<p class="date">December 4, 2017 at 3:12 pm </p>#}
{#									<p class="comment">#}
{#										Never say goodbye till the end comes!#}
{#									</p>#}
{#								</div>#}
{#							</div>#}
{#							<div class="reply-btn">#}
{#									<a href="" class="btn-reply text-uppercase">reply</a> #}
{#							</div>#}
{#						</div>#}
{#					</div>	#}
{#					<div class="comment-list">#}
{#						<div class="single-comment justify-content-between d-flex">#}
{#							<div class="user justify-content-between d-flex">#}
{#								<div class="thumb">#}
{#									<img src="{% static 'img/blog/c5.jpg' %}" alt="">#}
{#								</div>#}
{#								<div class="desc">#}
{#									<h5><a href="#">Ina Hayes</a></h5>#}
{#									<p class="date">December 4, 2017 at 3:12 pm </p>#}
{#									<p class="comment">#}
{#										Never say goodbye till the end comes!#}
{#									</p>#}
{#								</div>#}
{#							</div>#}
{#							<div class="reply-btn">#}
{#									<a href="" class="btn-reply text-uppercase">reply</a> #}
{#							</div>#}
{#						</div>#}
{#					</div>	                                             				#}
{#				</div>#}
{#				<div class="comment-form">#}
{#					<h4>Leave a Comment</h4>#}
{#					<form>#}
{#						<div class="form-group form-inline">#}
{#							<div class="form-group col-lg-6 col-md-12 name">#}
{#							<input type="text" class="form-control" id="name" placeholder="Enter Name" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter Name'">#}
{#							</div>#}
{#							<div class="form-group col-lg-6 col-md-12 email">#}
{#							<input type="email" class="form-control" id="email" placeholder="Enter email address" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter email address'">#}
{#							</div>#}
{#						</div>#}
{#						<div class="form-group">#}
{#							<input type="text" class="form-control" id="subject" placeholder="Subject" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Subject'">#}
{#						</div>#}
{#						<div class="form-group">#}
{#							<textarea class="form-control mb-10" rows="5" name="message" placeholder="Messege" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Messege'" required=""></textarea>#}
{#						</div>#}
{#						<a href="#" class="primary-btn text-uppercase">Post Comment</a>#}
{#					</form>#}
{#				</div>#}

            <div class="comments-area">
                <div id="disqus_thread"></div>
                <script>
                    /**
                    *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
                    *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables    */
                    /*
                    var disqus_config = function () {
                    this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
                    this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
                    };
                    */
                    (function() { // DON'T EDIT BELOW THIS LINE
                    var d = document, s = d.createElement('script');
                    s.src = 'https://travelista-1.disqus.com/embed.js';
                    s.setAttribute('data-timestamp', +new Date());
                    (d.head || d.body).appendChild(s);
                    })();
                </script>
                <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
            </div>
			</div>

            <!-- Sidebar Widget -->
			<div class="col-lg-4 sidebar-widgets">
				<div class="widget-wrap">
					
					{% include 'blog/blog-search.html' %}
					
					{% include 'blog/blog-user.html' %}

					{% latest_posts 5 %}
					
					{% include 'blog/blog-ads.html' %}
					
					{% include 'blog/blog-post-category.html' %}
					
					{% include 'blog/blog-newsletter.html' %}
					
					{% include 'blog/blog-cloud.html' %}
					
				</div>
			</div>
		</div>
	</div>	
</section>
<!-- End post-content Area -->
{% endblock content %}