Travelista/Travelista/urls.py
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.contrib.sites.models import Site
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

from apps.blog.sitemaps import BlogSitemap
from apps.mainPage.sitemaps import MainPageViewSitemap


def redirect_to_domain(request):
    current_site = Site.objects.get_current()
    redirect_url = f"https://{current_site.domain}"
    return RedirectView.as_view(url=redirect_url)(request)

sitemaps = {
    'index': MainPageViewSitemap,
    'blog': BlogSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.mainPage.urls')),
    path('blog/', include('apps.blog.urls')),

    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
    re_path(r'^robots\.txt', include('robots.urls')),

    path('accounts/', include('allauth.urls')),
    path('accounts/', include('allauth.socialaccount.urls')),
    path('', redirect_to_domain,),
]

# Manage static files and url through nginx in production
if settings.DEBUG == True:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls"))
    ]

Travelista/blog/urls.py
from django.urls import path
from blog.views import *

app_name = 'blog'

urlpatterns = [
    path('', blog_home, name='index'),
    path('single/<int:pid>', blog_single, name='single'),
    path('category/<str:cat_name>', blog_home, name='category'),
    path('author/<str:author>', blog_home, name='author'),
    path('search/',blog_search,name='search'),
]

Travelista/templates/Travelista/index/index-banner.html
{% load static %}
<!-- start banner Area -->
<section class="banner-area relative">
	<div class="overlay overlay-bg"></div>
	<div class="container">
		<div class="row fullscreen align-items-center justify-content-between">
			<div class="col-lg-6 col-md-6 banner-left">
				<h6 class="text-white">Away from monotonous life</h6>
				<h1 class="text-white">Magical Travel</h1>
				<p class="text-white">
					If you are looking at blank cassettes on the web, you may be very confused at the difference in price. You may see some for as low as $.17 each.
				</p>

			</div>

		</div>
	</div>
</section>
<!-- End banner Area -->

Travelista/templates/Travelista/index/index-blog-area.html
{% load static humanize %}
<!-- Start blog Area -->
<section class="recent-blog-area section-gap">
	<div class="container">
		<div class="row d-flex justify-content-center">
			<div class="menu-content pb-60 col-lg-9">
				<div class="title text-center">
					<h1 class="mb-10">Latest from Our Blog</h1>
					<p>With the exception of Nietzsche, no other madman has contributed so much to human sanity as has.</p>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="active-recent-blog-carusel">
                {% for post in latest_posts %}
                	<div class="single-recent-blog-post item">
					<div class="thumb">
						<img class="img-fluid" src="{{ post.img.url }}" alt="">
					</div>
					<div class="details">
						<div class="tags">
							<ul>
                                {% for category in post.category.all %}
                                    <li>
                                        <a href="{% url 'blog:category' cat_name=category %}">{{ category.name }}</a>
                                    </li>
                                {% endfor %}
							</ul>
						</div>
						<a href="{% url 'blog:single' post.id %}"><h4 class="title">{{ post.title }}</h4></a>
						<p>
							{{ post.content|truncatewords:20|striptags }}
						</p>
						<h6 class="date">{{ post.published_date|naturaltime }}</h6>
					</div>
				</div>
                {% endfor %}
			</div>
		</div>
	</div>
</section>
<!-- End recent-blog Area -->

Travelista/templates/Travelista/index/index-home-about.html
{% load static %}
<!-- Start home-about Area -->
<section class="home-about-area">
	<div class="container-fluid">
		<div class="row align-items-center justify-content-end">
			<div class="col-lg-6 col-md-12 home-about-left">
				<h1>
					Did not find your Package? <br>
					Feel free to ask us. <br>
					We‘ll make it for you
				</h1>
				<p>
					inappropriate behavior is often laughed off as “boys will be boys,” women face higher conduct standards especially in the workplace. That’s why it’s crucial that, as women, our behavior on the job is beyond reproach. inappropriate behavior is often laughed.
				</p>
				<a href="#" class="primary-btn text-uppercase">request custom price</a>
			</div>
			<div class="col-lg-6 col-md-12 home-about-right no-padding">
				<img class="img-fluid" src="{% static 'img/about-img.jpg' %}" alt="">
			</div>
		</div>
	</div>
</section>
<!-- End home-about Area -->

Travelista/templates/Travelista/index/index-other-issue.html
{% load static %}
<!-- Start other-issue Area -->
<section class="other-issue-area section-gap">
	<div class="container">
		<div class="row d-flex justify-content-center">
			<div class="menu-content pb-70 col-lg-9">
				<div class="title text-center">
					<h1 class="mb-10">Other issues we can help you with</h1>
					<p>We all live in an age that belongs to the young at heart. Life that is.</p>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-lg-3 col-md-6">
				<div class="single-other-issue">
					<div class="thumb">
						<img class="img-fluid" src="{% static 'img/o1.jpg' %}" alt="">
					</div>
					<a href="#">
						<h4>Rent a Car</h4>
					</a>
					<p>
						The preservation of human life is the ultimate value, a pillar of ethics and the foundation.
					</p>
				</div>
			</div>
			<div class="col-lg-3 col-md-6">
				<div class="single-other-issue">
					<div class="thumb">
						<img class="img-fluid" src="{% static 'img/o2.jpg' %}" alt="">
					</div>
					<a href="#">
						<h4>Cruise Booking</h4>
					</a>
					<p>
						I was always somebody who felt quite sorry for myself, what I had not got compared.
					</p>
				</div>
			</div>
			<div class="col-lg-3 col-md-6">
				<div class="single-other-issue">
					<div class="thumb">
						<img class="img-fluid" src="{% static 'img/o3.jpg' %}" alt="">
					</div>
					<a href="#">
						<h4>To Do List</h4>
					</a>
					<p>
						The following article covers a topic that has recently moved to center stage–at least it seems.
					</p>
				</div>
			</div>
			<div class="col-lg-3 col-md-6">
				<div class="single-other-issue">
					<div class="thumb">
						<img class="img-fluid" src="{% static 'img/o4.jpg' %}" alt="">
					</div>
					<a href="#">
						<h4>Food Features</h4>
					</a>
					<p>
						There are many kinds of narratives and organizing principles. Science is driven by evidence.
					</p>
				</div>
			</div>
		</div>
	</div>
</section>
<!-- End other-issue Area -->

Travelista/templates/Travelista/index/index-popular-dest.html
{% load static %}
<!-- Start popular-destination Area -->
<section class="popular-destination-area section-gap">
	<div class="container">
		<div class="row d-flex justify-content-center">
			<div class="menu-content pb-70 col-lg-8">
				<div class="title text-center">
					<h1 class="mb-10">Popular Destinations</h1>
					<p>We all live in an age that belongs to the young at heart. Life that is becoming extremely fast, day.</p>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-lg-4">
				<div class="single-destination relative">
					<div class="thumb relative">
						<div class="overlay overlay-bg"></div>
						<img class="img-fluid" src="{% static 'img/d1.jpg' %}" alt="">
					</div>
					<div class="desc">
						<a href="#" class="price-btn">$150</a>
						<h4>Mountain River</h4>
						<p>Paraguay</p>
					</div>
				</div>
			</div>
			<div class="col-lg-4">
				<div class="single-destination relative">
					<div class="thumb relative">
						<div class="overlay overlay-bg"></div>
						<img class="img-fluid" src="{% static 'img/d2.jpg' %}" alt="">
					</div>
					<div class="desc">
						<a href="#" class="price-btn">$250</a>
						<h4>Dream City</h4>
						<p>Paris</p>
					</div>
				</div>
			</div>
			<div class="col-lg-4">
				<div class="single-destination relative">
					<div class="thumb relative">
						<div class="overlay overlay-bg"></div>
						<img class="img-fluid" src="{% static 'img/d3.jpg' %}" alt="">
					</div>
					<div class="desc">
						<a href="#" class="price-btn">$350</a>
						<h4>Cloud Mountain</h4>
						<p>Sri Lanka</p>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
<!-- End popular-destination Area -->

Travelista/templates/Travelista/index/index.html
{% extends 'base.html' %}
{% load static index_tags %}

{% block content %}
    {% include './index-banner.html' %}

    {% include './index-popular-dest.html' %}

    {% include './index-other-issue.html' %}

    {% include './index-home-about.html' %}

    {% latest_posts 6 %}

{% endblock content %}